services:
  vite-protocolo:
    build:
      context: ./vite-protocolo/
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3010:5173"
    env_file:
      - .env
    networks:
      - protocolo-network

  spring-protocolo:
    build:
      context: ./spring-protocolo/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - protocolo-network

networks:
  protocolo-network:
    driver: bridge