services:
  vite-protocolo:
    build:
      context: ./vite-protocolo/
      dockerfile: Dockerfile
    volumes:
      - ./vite-protocolo:/app
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - protocolo-network

  spring-protocolo:
    build:
      context: ./spring-protocolo/
      dockerfile: Dockerfile
    ports:
      - "${AVC_BACK_PORT}:8080"
    env_file:
      - .env
    networks:
      - protocolo-network

networks:
  protocolo-network:
    driver: bridge
